trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - arm/
    - .azure/pipelines/
    - src/

name: $(Date:yyyyMMdd)$(Rev:.r).$(Build.SourceBranch)

parameters:
- name: overrideDeploy
  displayName: Trigger deploy if not on master branch?
  type: boolean
  default: false
- name: resourceGroupNameBase
  displayName: Resource Group base name to use if deploying ('useDefault' pulls from config)
  type: string
  default: useDefault
- name: environmentSuffix
  displayName: Environment
  type: string
  default: dev
  values:
  - dev
  - qa
  - prod
- name: enableAuthentication
  displayName: Configure the application to use Azure AD for Authentication?
  type: boolean
  default: false

variables:
- template: variables.yml # Generic and/or generated variables
- template: variables-azure.yml # Deployment related (groups or portal variables work too)
  parameters:
    resourceGroupNameBase: ${{ parameters.resourceGroupNameBase }}
    baseName: # Leave empty to build name based on resource group and location
    environmentSuffix: ${{ parameters.environmentSuffix }}
    enableAuthentication: ${{ parameters.enableAuthentication }}
# Include a group if you prefer that over yaml for things like secrets and service connection names
# Hardcoding or specifying as a parameter both work
#- group: groupName | ${{ parameters.variableGroupName }}
- ${{ if parameters.enableAuthentication }}:
  - group: sample-template-authentication
- name: shouldDeploy # Only run deployment when merging to master unless specifically configured during manual run
  value: >-
    $[or(
      eq(variables['isMasterMerge'], 'True'),
      ${{ parameters.overrideDeploy }}
    )]

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build
    displayName: Build ASP.NET Core App 3.1
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build $(buildConfiguration)
      inputs:
        command: build
        projects: $(solutionPath)
        arguments: --configuration $(buildConfiguration) $(buildAdditionalCliParameters)

    - task: DotNetCoreCLI@2
      displayName: Run Unit Tests and Code Coverage
      inputs:
        command: test
        projects: $(solutionPath)
        arguments: --configuration $(buildConfiguration) --settings coverlet.runsettings.xml

    - task: DotNetCoreCLI@2
      displayName: Install ReportGenerator Tool
      inputs:
        command: custom
        custom: tool
        arguments: install --tool-path . dotnet-reportgenerator-globaltool

    - script: |
        ./reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:Cobertura
      displayName: Create Code Coverage Report

    - task: PublishCodeCoverageResults@1
      displayName: Publish Code Coverage Report
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: $(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml

    - script: |
        dotnet publish $(solutionPath) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
      displayName: Publish Web App

#    - task: CopyFiles@2
#      displayName: Copy ARM template to ArtifactStagingDirectory
#      inputs:
#        sourceFolder: arm
#        contents: '*'
#        targetFolder: $(Build.ArtifactStagingDirectory)/arm

    - task: PublishPipelineArtifact@1 # Microsoft recommends this over PublishBuildArtifacts
      displayName: Publish Pipeline Artifacts
      condition: and(succeeded(), eq(variables['shouldDeploy'], 'True'))
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: $(artifactName)

    - script: |
        pwd
        printenv | sort
        ls -R $(Pipeline.Workspace)
      displayName: Debug script
      condition: always()

- stage: deploy
  displayName: Deploy
  condition: and(succeeded(), eq(variables['shouldDeploy'], 'True'))
  jobs:
  - deployment: deploy
    displayName: Deploy ASP.NET Core App 3.1
    environment: $(environmentName)
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureResourceGroupDeployment@2
            displayName: Azure Deployment
            inputs:
              azureSubscription: $(azureSubscriptionServiceConnectionName)
              action: Create Or Update Resource Group
              resourceGroupName: $(resourceGroupName)
              location: $(location)
              csmFile: $(Pipeline.Workspace)/$(artifactName)/$(armTemplateFileArtifactPath)
              deploymentMode: Complete
              deploymentName: $(deploymentName)
              deploymentOutputs: ArmDeploymentOutput
              overrideParameters: >-
                -name $(armTemplateNameParameter)
                -additionalSecrets $(additionalKeyVaultSecrets)
          - pwsh: |
              $output = ConvertFrom-Json '$(ArmDeploymentOutput)' -Depth 10

              $WebAppName  = $output.result.value.WebAppName

              Write-Host "##vso[task.setvariable variable=WEB_APP_NAME]$WebAppName"
            failOnStderr: true
            displayName: Create variables from ARM deployment outputs

          - task: AzureRmWebAppDeployment@4
            displayName: Azure App Service Deploy
            inputs:
              azureSubscription: $(azureSubscriptionServiceConnectionName)
              resourceGroupName: $(resourceGroupName)
              webAppName: $(WEB_APP_NAME)
              webAppKind: webAppLinux
              packageForLinux: $(Pipeline.Workspace)/$(artifactName)/$(webAppProjectName).zip
              runtimeStack: DOTNETCORE|3.1
              startupCommand: /home/site/wwwroot/$(webAppProjectName)

          - script: |
              echo $(ArmDeploymentOutput)
              pwd
              printenv | sort
              ls -R $(Pipeline.Workspace)
            displayName: Debug script
            condition: always()
